'use client'

import React, { useMemo, useState, useCallback } from 'react'

interface Props {
  content: string
  isHtml: boolean
  itemType?: string
}

// ── Content Size Thresholds ──────────────────────────────────────────────
const TRUNCATE_WORD_LIMIT = 3000          // Show "Read more" after this
const TRUNCATE_CHAR_LIMIT = 15000         // Char-based fallback
const SECTION_COLLAPSE_THRESHOLD = 8000   // Collapse sections in docs this big (words)

// ── AI Chat Artifact Patterns ────────────────────────────────────────────
const UI_CHROME_PATTERNS: RegExp[] = [
  /^(Create Web Page|View|Click to open|Edit in AI Developer|Using Tool|Image Generation)\s*$/gm,
  /^\|?\s*(Image Generation|Web Search|Code Execution)\s*\|?\s*$/gm,
  /^Tab \d+\s*$/gm,
  /^Mixture-of-Agents\s*$/gm,
  /^(gpt-5|gpt-4o?|claude-3|claude-\d|gemini-\d|deepseek-\w+)\s*$/gmi,
  /^(agentic_\w+|Click to open)\s*$/gm,
]

// ── Genspark-specific chrome patterns ────────────────────────────────────
const GENSPARK_CHROME_PATTERNS: RegExp[] = [
  // "Generated with sparks and insights from [N sources](prompt://...)"
  /Generated with sparks and insights from \[.*?\]\(prompt:\/\/.*?\)\s*/g,
  // Any prompt:// URLs and their markdown link wrappers
  /\[([^\]]*)\]\(prompt:\/\/[^)]+\)/g,
  // Bare prompt:// URLs
  /prompt:\/\/[^\s)]+/g,
  // "Generated by <Name>Public" or "Generated by <Name>"
  /Generated by [A-Z][a-z]+ [A-Z]\.?\s*Public\s*/g,
  /Generated by [A-Z][a-z]+ [A-Z]\.?\s*(?=\n|$)/g,
  // Profile image markdown at start
  /^!\[\]\(https:\/\/lh3\.googleusercontent\.com\/[^\)]+\)\s*/gm,
  // Empty headings (# with no text)
  /^#{1,6}\s*$/gm,
  // Duplicate title line right after H1 (title repeated as plain text)
  // We handle this in cleanContent below
]

function cleanContent(text: string, title?: string): string {
  let cleaned = text

  // Apply UI chrome patterns
  for (const pattern of UI_CHROME_PATTERNS) {
    cleaned = cleaned.replace(new RegExp(pattern.source, pattern.flags), '')
  }

  // Apply Genspark-specific patterns
  for (const pattern of GENSPARK_CHROME_PATTERNS) {
    cleaned = cleaned.replace(new RegExp(pattern.source, pattern.flags), '')
  }

  // Remove duplicate title text right after H1
  // Pattern: "# Title\n\nTitle" or "# Title\n\nTitleGenerated..."
  if (title && title.length > 10) {
    const escapedTitle = title.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    // Remove the duplicate title that appears right after the heading
    const dupPattern = new RegExp(`(^#\\s+${escapedTitle}\\s*\\n+)${escapedTitle}`, 'm')
    cleaned = cleaned.replace(dupPattern, '$1')
    // Also catch the case without the heading
    const bareDup = new RegExp(`^${escapedTitle}\\s*(?:Generated|\\n)`, 'm')
    if (cleaned.indexOf(`# ${title}`) !== -1) {
      // Title exists as heading, remove bare duplicate
      cleaned = cleaned.replace(bareDup, '')
    }
  }

  // Clean up excessive whitespace
  cleaned = cleaned.replace(/\n{4,}/g, '\n\n\n')
  cleaned = cleaned.replace(/\r\n/g, '\n')

  return cleaned.trim()
}

// ── Detect content type ──────────────────────────────────────────────────
function detectContentFormat(content: string): 'chat' | 'html-interactive' | 'markdown' | 'plain' {
  // Check for full HTML pages (interactive Genspark sites)
  if (/<html[\s>]/i.test(content.slice(0, 500)) ||
      (/<style[\s>]/i.test(content.slice(0, 2000)) && /<div[\s>]/i.test(content.slice(0, 2000)))) {
    return 'html-interactive'
  }

  const lines = content.split('\n').slice(0, 30)
  const chatLineCount = lines.filter(l => /^(User|Assistant|Human|AI|System)\s*[:>]/i.test(l.trim())).length
  if (chatLineCount >= 3) return 'chat'

  const mdIndicators = lines.filter(l =>
    /^#{1,6}\s/.test(l.trim()) ||
    /^\*\*[^*]+\*\*/.test(l.trim()) ||
    /^[-*]\s/.test(l.trim()) ||
    /^\d+\.\s/.test(l.trim()) ||
    /^```/.test(l.trim()) ||
    /^\|.+\|/.test(l.trim())
  ).length
  if (mdIndicators >= 3) return 'markdown'
  return 'plain'
}

// ── Word counting ────────────────────────────────────────────────────────
function countWords(text: string): number {
  return text.split(/\s+/).filter(w => w.length > 0).length
}

// ── Table of Contents ────────────────────────────────────────────────────
interface TocEntry { id: string; level: number; text: string }

function extractToc(content: string, isHtml: boolean): TocEntry[] {
  const entries: TocEntry[] = []
  if (isHtml) {
    const re = /<h([1-3])[^>]*>([^<]+)<\/h\1>/gi
    let match
    while ((match = re.exec(content)) !== null) {
      const id = match[2].toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
      entries.push({ id, level: parseInt(match[1]), text: match[2].trim() })
    }
  } else {
    const lines = content.split('\n')
    for (const line of lines) {
      const m = line.match(/^(#{1,3})\s+(.+)/)
      if (m) {
        const text = m[2].replace(/\*\*/g, '').trim()
        if (text.length === 0) continue
        const id = text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
        entries.push({ id, level: m[1].length, text })
      }
    }
  }
  return entries
}

// ── Sticky ToC Sidebar ───────────────────────────────────────────────────
function TableOfContents({ entries }: { entries: TocEntry[] }) {
  if (entries.length < 3) return null
  const [isOpen, setIsOpen] = useState(true)
  const displayEntries = entries.length > 30 ? entries.filter(e => e.level <= 2) : entries

  return (
    <nav className="kb-toc mb-8 rounded-xl border border-gray-200 dark:border-gray-800 bg-gray-50/80 dark:bg-gray-900/60 p-5 backdrop-blur-sm">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between text-xs font-bold text-gray-500 dark:text-gray-400 uppercase tracking-widest"
      >
        <span className="flex items-center gap-2">
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 10h16M4 14h16M4 18h16" />
          </svg>
          On This Page ({entries.length} sections)
        </span>
        <svg className={`w-4 h-4 transform transition-transform ${isOpen ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      {isOpen && (
        <ul className="mt-3 space-y-1 max-h-[400px] overflow-y-auto">
          {displayEntries.map((e, i) => (
            <li key={i} style={{ paddingLeft: `${(e.level - 1) * 16}px` }}>
              <a
                href={`#${e.id}`}
                className="text-sm text-gray-600 dark:text-gray-400 hover:text-amber-600 dark:hover:text-amber-400 transition-colors leading-relaxed block py-0.5 truncate"
              >
                {e.text}
              </a>
            </li>
          ))}
          {entries.length > 30 && displayEntries.length < entries.length && (
            <li className="text-xs text-gray-400 italic pt-2">
              + {entries.length - displayEntries.length} subsections
            </li>
          )}
        </ul>
      )}
    </nav>
  )
}

// ── Content Truncation Wrapper ───────────────────────────────────────────
function TruncatedContent({
  content,
  wordLimit,
  children,
  renderFull,
}: {
  content: string
  wordLimit: number
  children: React.ReactNode
  renderFull: () => React.ReactNode
}) {
  const [expanded, setExpanded] = useState(false)
  const wordCount = useMemo(() => countWords(content), [content])
  const needsTruncation = wordCount > wordLimit

  if (!needsTruncation || expanded) {
    return (
      <>
        {expanded ? renderFull() : children}
        {expanded && needsTruncation && (
          <div className="mt-8 text-center">
            <button
              onClick={() => setExpanded(false)}
              className="px-6 py-2 rounded-full bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 text-sm font-medium hover:bg-gray-200 dark:hover:bg-gray-700 transition-colors"
            >
              ▲ Collapse content
            </button>
          </div>
        )}
      </>
    )
  }

  return (
    <>
      <div className="relative">
        {children}
        <div className="absolute bottom-0 left-0 right-0 h-48 bg-gradient-to-t from-white dark:from-gray-950 to-transparent pointer-events-none" />
      </div>
      <div className="mt-2 text-center relative z-10">
        <div className="inline-flex flex-col items-center gap-2 bg-white dark:bg-gray-950 px-8 py-4 rounded-2xl border border-gray-200 dark:border-gray-800 shadow-lg">
          <span className="text-sm text-gray-500 dark:text-gray-400">
            Showing first ~{wordLimit.toLocaleString()} of {wordCount.toLocaleString()} words
          </span>
          <button
            onClick={() => setExpanded(true)}
            className="px-8 py-2.5 rounded-full bg-amber-500 hover:bg-amber-600 text-white text-sm font-semibold transition-colors shadow-md hover:shadow-lg"
          >
            Show full content ▼
          </button>
        </div>
      </div>
    </>
  )
}

// ── Interactive HTML Renderer (iframe sandbox) ───────────────────────────
function InteractiveHtmlRenderer({ content }: { content: string }) {
  const [expanded, setExpanded] = useState(false)
  const iframeHeight = expanded ? '80vh' : '600px'

  // Create a blob URL for the HTML content
  const blobUrl = useMemo(() => {
    const blob = new Blob([content], { type: 'text/html' })
    return URL.createObjectURL(blob)
  }, [content])

  return (
    <div className="my-6">
      <div className="flex items-center justify-between mb-3 px-1">
        <div className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
          <span className="text-lg">🌐</span>
          <span className="font-medium">Interactive Page</span>
          <span className="text-xs bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 px-2 py-0.5 rounded-full">
            Live Preview
          </span>
        </div>
        <button
          onClick={() => setExpanded(!expanded)}
          className="text-xs font-medium text-gray-500 dark:text-gray-400 hover:text-amber-600 dark:hover:text-amber-400 transition-colors flex items-center gap-1"
        >
          {expanded ? '↙ Collapse' : '↗ Expand'}
        </button>
      </div>
      <div
        className="rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden shadow-md"
        style={{ height: iframeHeight }}
      >
        <iframe
          src={blobUrl}
          className="w-full h-full"
          sandbox="allow-scripts allow-same-origin"
          title="Interactive content preview"
          loading="lazy"
        />
      </div>
    </div>
  )
}

// ── Chat Renderer ────────────────────────────────────────────────────────
function ChatRenderer({ text }: { text: string }) {
  const messages: { role: string; content: string }[] = []
  const lines = text.split('\n')
  let currentRole = ''
  let currentContent: string[] = []

  for (const line of lines) {
    const m = line.match(/^(User|Assistant|Human|AI|System)\s*[:>]\s*(.*)/i)
    if (m) {
      if (currentRole) {
        messages.push({ role: currentRole, content: currentContent.join('\n').trim() })
      }
      currentRole = m[1].toLowerCase()
      currentContent = m[2] ? [m[2]] : []
    } else if (currentRole) {
      currentContent.push(line)
    }
  }
  if (currentRole) {
    messages.push({ role: currentRole, content: currentContent.join('\n').trim() })
  }

  if (messages.length === 0) return <MarkdownRenderer text={text} />

  return (
    <div className="space-y-4">
      {messages.map((msg, i) => {
        const isUser = ['user', 'human'].includes(msg.role)
        return (
          <div key={i} className={`flex ${isUser ? 'justify-end' : 'justify-start'}`}>
            <div className={`max-w-[85%] rounded-2xl px-5 py-3.5 ${
              isUser
                ? 'bg-amber-500/10 dark:bg-amber-500/10 border border-amber-200 dark:border-amber-800/50'
                : 'bg-gray-50 dark:bg-gray-800/70 border border-gray-200 dark:border-gray-700'
            }`}>
              <div className={`text-[10px] font-bold uppercase tracking-widest mb-1.5 ${
                isUser ? 'text-amber-600 dark:text-amber-400' : 'text-gray-400 dark:text-gray-500'
              }`}>
                {isUser ? '👤 You' : '🤖 Assistant'}
              </div>
              <div className="text-gray-700 dark:text-gray-300 leading-7 text-sm">
                <MarkdownRenderer text={msg.content} />
              </div>
            </div>
          </div>
        )
      })}
    </div>
  )
}

// ── Main Export ───────────────────────────────────────────────────────────
export function KBContentRenderer({ content, isHtml, itemType }: Props) {
  if (!content) return null

  // Extract title from first H1 for dedup
  const titleMatch = content.match(/^#\s+(.+)/m)
  const extractedTitle = titleMatch ? titleMatch[1].trim() : undefined

  const cleaned = useMemo(() => cleanContent(content, extractedTitle), [content, extractedTitle])
  const toc = useMemo(() => extractToc(cleaned, isHtml), [cleaned, isHtml])
  const format = useMemo(() => isHtml ? 'html' : detectContentFormat(cleaned), [cleaned, isHtml])
  const showToc = toc.length >= 3 && cleaned.length > 2000
  const wordCount = useMemo(() => countWords(cleaned), [cleaned])

  // ── Interactive HTML pages (Genspark spark pages, etc.) ──
  if (format === 'html-interactive') {
    return (
      <div>
        <InteractiveHtmlRenderer content={cleaned} />
        <details className="mt-4">
          <summary className="text-sm text-gray-500 dark:text-gray-400 cursor-pointer hover:text-amber-600 dark:hover:text-amber-400 transition-colors font-medium">
            View source code
          </summary>
          <pre className="mt-2 p-4 bg-gray-950 rounded-xl text-xs text-gray-300 overflow-x-auto max-h-[500px] overflow-y-auto">
            <code>{cleaned.slice(0, 50000)}</code>
          </pre>
        </details>
      </div>
    )
  }

  // ── Standard HTML ──
  if (isHtml) {
    let htmlWithIds = cleaned
    const re = /<h([1-6])([^>]*)>([^<]+)<\/h\1>/gi
    htmlWithIds = htmlWithIds.replace(re, (_match, level, attrs, text) => {
      const id = text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
      if (attrs.includes('id=')) return _match
      return `<h${level}${attrs} id="${id}">${text}</h${level}>`
    })

    const truncatedHtml = wordCount > TRUNCATE_WORD_LIMIT
      ? htmlWithIds.slice(0, TRUNCATE_CHAR_LIMIT)
      : htmlWithIds

    const renderHtml = (html: string) => (
      <>
        {showToc && <TableOfContents entries={toc} />}
        <div className="kb-html-content" dangerouslySetInnerHTML={{ __html: html }} />
      </>
    )

    if (wordCount > TRUNCATE_WORD_LIMIT) {
      return (
        <TruncatedContent
          content={cleaned}
          wordLimit={TRUNCATE_WORD_LIMIT}
          renderFull={() => renderHtml(htmlWithIds)}
        >
          {renderHtml(truncatedHtml)}
        </TruncatedContent>
      )
    }

    return renderHtml(htmlWithIds)
  }

  // ── Chat format ──
  if (format === 'chat') {
    return (
      <>
        <div className="mb-6 flex items-center gap-2 rounded-lg bg-blue-50 dark:bg-blue-900/15 border border-blue-200 dark:border-blue-800 px-4 py-2.5">
          <span className="text-blue-500">💬</span>
          <span className="text-xs font-medium text-blue-700 dark:text-blue-300">This item contains a conversation transcript</span>
        </div>
        <ChatRenderer text={cleaned} />
      </>
    )
  }

  // ── Markdown format (most content) ──
  // For massive docs, truncate and show expand button
  if (wordCount > TRUNCATE_WORD_LIMIT) {
    // Find a good truncation point (at a heading or paragraph boundary)
    const lines = cleaned.split('\n')
    let charCount = 0
    let truncLine = 0
    for (let i = 0; i < lines.length; i++) {
      charCount += lines[i].length + 1
      if (charCount > TRUNCATE_CHAR_LIMIT) {
        truncLine = i
        break
      }
    }
    const truncatedText = lines.slice(0, truncLine).join('\n')

    return (
      <TruncatedContent
        content={cleaned}
        wordLimit={TRUNCATE_WORD_LIMIT}
        renderFull={() => (
          <>
            {showToc && <TableOfContents entries={toc} />}
            <MarkdownRenderer text={cleaned} />
          </>
        )}
      >
        {showToc && <TableOfContents entries={toc} />}
        <MarkdownRenderer text={truncatedText} />
      </TruncatedContent>
    )
  }

  return (
    <>
      {showToc && <TableOfContents entries={toc} />}
      <MarkdownRenderer text={cleaned} />
    </>
  )
}

// ── Markdown Renderer ──────────────────────────────────────────────────────

function MarkdownRenderer({ text }: { text: string }) {
  const blocks = useMemo(() => parseBlocks(text), [text])
  return <div className="kb-md-content">{blocks.map((block, i) => renderBlock(block, i))}</div>
}

type Block =
  | { type: 'heading'; level: number; text: string; id: string }
  | { type: 'paragraph'; text: string }
  | { type: 'code'; lang: string; code: string }
  | { type: 'blockquote'; text: string }
  | { type: 'callout'; kind: 'info' | 'warning' | 'tip' | 'note'; text: string }
  | { type: 'hr' }
  | { type: 'list'; ordered: boolean; items: string[] }
  | { type: 'table'; headers: string[]; rows: string[][] }
  | { type: 'image'; src: string; alt: string }
  | { type: 'html-embed'; html: string }
  | { type: 'empty' }

function parseBlocks(text: string): Block[] {
  const lines = text.split('\n')
  const blocks: Block[] = []
  let i = 0

  while (i < lines.length) {
    const line = lines[i]
    const trimmed = line.trim()

    if (trimmed === '') { i++; continue }

    // Fenced code block
    if (trimmed.startsWith('```')) {
      const lang = trimmed.slice(3).trim()
      const codeLines: string[] = []
      i++
      while (i < lines.length && !lines[i].trim().startsWith('```')) {
        codeLines.push(lines[i])
        i++
      }
      i++
      blocks.push({ type: 'code', lang, code: codeLines.join('\n') })
      continue
    }

    // ── Embedded HTML pages (<!DOCTYPE html> or <html> blocks inside markdown) ──
    if (/^<!doctype\s+html/i.test(trimmed) || /^<html[\s>]/i.test(trimmed)) {
      const htmlLines: string[] = [line]
      i++
      let depth = 1
      while (i < lines.length) {
        htmlLines.push(lines[i])
        if (/<html[\s>]/i.test(lines[i])) depth++
        if (/<\/html>/i.test(lines[i])) { depth--; if (depth <= 0) { i++; break } }
        i++
      }
      blocks.push({ type: 'html-embed', html: htmlLines.join('\n') })
      continue
    }
    // Also catch <style> ... </style> ... <div> blocks that form a standalone interactive page
    if (/^<style[\s>]/i.test(trimmed) && !trimmed.includes('</style>')) {
      // Look ahead: if we find </style> and then <div> tags, this is an interactive HTML block
      let j = i + 1
      let foundStyleEnd = false
      while (j < lines.length && j < i + 200) {
        if (/<\/style>/i.test(lines[j])) { foundStyleEnd = true; break }
        j++
      }
      if (foundStyleEnd) {
        // Check if there's HTML structure after the style block
        let hasHtmlStructure = false
        for (let k = j + 1; k < Math.min(j + 10, lines.length); k++) {
          if (/<div[\s>]/i.test(lines[k]) || /<body[\s>]/i.test(lines[k]) || /<section[\s>]/i.test(lines[k])) {
            hasHtmlStructure = true
            break
          }
        }
        if (hasHtmlStructure) {
          // Collect everything from <style> to the end of the HTML structure
          const htmlLines: string[] = []
          while (i < lines.length) {
            htmlLines.push(lines[i])
            // Stop at </html>, </body>, or when we hit markdown again after closing tags
            if (/<\/html>/i.test(lines[i]) || /<\/body>/i.test(lines[i])) { i++; break }
            // If we've passed the style block and hit a blank line followed by markdown
            if (i > j + 5 && lines[i].trim() === '' && i + 1 < lines.length) {
              const next = lines[i + 1].trim()
              if (/^#{1,6}\s/.test(next) || /^[-*]\s/.test(next) || /^\d+\.\s/.test(next)) { i++; break }
            }
            i++
          }
          // Wrap in proper HTML if needed
          let html = htmlLines.join('\n')
          if (!/<html/i.test(html)) {
            html = `<!DOCTYPE html><html><head><meta charset="utf-8"></head><body>${html}</body></html>`
          }
          blocks.push({ type: 'html-embed', html })
          continue
        }
      }
    }

    // Horizontal rule
    if (/^[-*_]{3,}$/.test(trimmed)) {
      blocks.push({ type: 'hr' })
      i++
      continue
    }

    // Image (standalone markdown image)
    const imgMatch = trimmed.match(/^!\[([^\]]*)\]\(([^)]+)\)$/)
    if (imgMatch) {
      blocks.push({ type: 'image', alt: imgMatch[1], src: imgMatch[2] })
      i++
      continue
    }

    // ── Table Detection (standard markdown + loose pipe-delimited) ──────
    // Standard markdown: | Header | Header | \n |---|---| \n | Cell | Cell |
    if (trimmed.startsWith('|') && trimmed.endsWith('|') && i + 1 < lines.length && /^\|[\s:-]+\|/.test(lines[i + 1]?.trim())) {
      const headers = trimmed.split('|').filter(c => c.trim()).map(c => c.trim())
      i += 2
      const rows: string[][] = []
      while (i < lines.length && lines[i].trim().startsWith('|')) {
        rows.push(lines[i].split('|').filter(c => c.trim()).map(c => c.trim()))
        i++
      }
      blocks.push({ type: 'table', headers, rows })
      continue
    }

    // Loose pipe-delimited tables (Genspark style):
    //   Step | Tool | Actions | Inputs
    //   1. Do X | Paper | Write it | Data
    //   2. Do Y | Google | Open it | List
    // Detect: current line has 2+ pipes AND next 2+ lines also have similar pipe count
    {
      const pipeCount = (trimmed.match(/\|/g) || []).length
      if (pipeCount >= 2 && !trimmed.startsWith('#') && !trimmed.startsWith('>') && !trimmed.startsWith('```')) {
        // Look ahead: need at least 2 consecutive lines with similar pipe count
        let tableEnd = i + 1
        while (tableEnd < lines.length) {
          const nextTrimmed = lines[tableEnd].trim()
          if (nextTrimmed === '') break
          const nextPipes = (nextTrimmed.match(/\|/g) || []).length
          // Skip separator rows (|---|---|)
          if (/^[\s|:-]+$/.test(nextTrimmed)) { tableEnd++; continue }
          // Allow pipe count to vary by ±1 (some rows have merged cells)
          if (nextPipes < pipeCount - 1 || nextPipes > pipeCount + 1) break
          tableEnd++
        }
        const rowCount = tableEnd - i
        if (rowCount >= 3) {
          // First non-separator line = headers, rest = rows
          let headerIdx = i
          // Skip separator if it's right after first line
          const secondLine = lines[i + 1]?.trim() || ''
          const skipSecond = /^[\s|:-]+$/.test(secondLine)
          
          const headerLine = lines[headerIdx].trim()
          const headers = headerLine.split('|').map(c => c.trim()).filter(c => c.length > 0)
          
          const dataStart = skipSecond ? i + 2 : i + 1
          const rows: string[][] = []
          for (let r = dataStart; r < tableEnd; r++) {
            const rowLine = lines[r].trim()
            if (/^[\s|:-]+$/.test(rowLine)) continue // Skip separator rows
            const cells = rowLine.split('|').map(c => c.trim()).filter(c => c.length > 0)
            if (cells.length > 0) rows.push(cells)
          }
          
          if (rows.length >= 2) {
            blocks.push({ type: 'table', headers, rows })
            i = tableEnd
            continue
          }
        }
      }
    }

    // Headings
    const headingMatch = trimmed.match(/^(#{1,6})\s+(.+)/)
    if (headingMatch) {
      const hText = headingMatch[2]
      if (hText.trim().length === 0) { i++; continue } // Skip empty headings
      const id = hText.replace(/\*\*/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
      blocks.push({ type: 'heading', level: headingMatch[1].length, text: hText, id })
      i++
      continue
    }

    // Blockquote / Callout
    if (trimmed.startsWith('> ')) {
      const quoteLines: string[] = []
      while (i < lines.length && lines[i].trim().startsWith('> ')) {
        quoteLines.push(lines[i].trim().slice(2))
        i++
      }
      const joined = quoteLines.join('\n')
      if (/^[ℹ️📘🔵]/.test(joined)) {
        blocks.push({ type: 'callout', kind: 'info', text: joined.replace(/^[ℹ️📘🔵]\s*/, '') })
      } else if (/^[⚠️🔶🟡]/.test(joined)) {
        blocks.push({ type: 'callout', kind: 'warning', text: joined.replace(/^[⚠️🔶🟡]\s*/, '') })
      } else if (/^[💡✨🟢]/.test(joined)) {
        blocks.push({ type: 'callout', kind: 'tip', text: joined.replace(/^[💡✨🟢]\s*/, '') })
      } else if (/^[📝📋]/.test(joined)) {
        blocks.push({ type: 'callout', kind: 'note', text: joined.replace(/^[📝📋]\s*/, '') })
      } else {
        blocks.push({ type: 'blockquote', text: joined })
      }
      continue
    }

    // Unordered list
    if (/^[\-\*]\s/.test(trimmed)) {
      const items: string[] = []
      while (i < lines.length && /^[\s]*[\-\*]\s/.test(lines[i])) {
        items.push(lines[i].replace(/^[\s]*[\-\*]\s/, ''))
        i++
      }
      blocks.push({ type: 'list', ordered: false, items })
      continue
    }

    // Ordered list
    if (/^\d+\.\s/.test(trimmed)) {
      const items: string[] = []
      while (i < lines.length && /^[\s]*\d+\.\s/.test(lines[i])) {
        items.push(lines[i].replace(/^[\s]*\d+\.\s*/, ''))
        i++
      }
      blocks.push({ type: 'list', ordered: true, items })
      continue
    }

    // Paragraph
    const paraLines: string[] = []
    while (
      i < lines.length &&
      lines[i].trim() !== '' &&
      !lines[i].trim().startsWith('#') &&
      !lines[i].trim().startsWith('```') &&
      !lines[i].trim().startsWith('> ') &&
      !/^[-*_]{3,}$/.test(lines[i].trim()) &&
      !/^[\-\*]\s/.test(lines[i].trim()) &&
      !/^\d+\.\s/.test(lines[i].trim()) &&
      !(lines[i].trim().startsWith('|') && lines[i].trim().endsWith('|'))
    ) {
      paraLines.push(lines[i])
      i++
    }
    if (paraLines.length > 0) {
      const joined = paraLines.join('\n')
      if (joined.length > 800) {
        const sentences = joined.split(/(?<=[.!?])\s+(?=[A-Z])/)
        let current: string[] = []
        for (const s of sentences) {
          current.push(s)
          if (current.join(' ').length > 500) {
            blocks.push({ type: 'paragraph', text: current.join(' ') })
            current = []
          }
        }
        if (current.length) blocks.push({ type: 'paragraph', text: current.join(' ') })
      } else {
        blocks.push({ type: 'paragraph', text: joined })
      }
    }
  }

  return blocks
}

function renderBlock(block: Block, key: number): React.ReactNode {
  switch (block.type) {
    case 'heading': {
      const Tag = `h${block.level}` as keyof JSX.IntrinsicElements
      const classes: Record<number, string> = {
        1: 'text-3xl font-extrabold mt-12 mb-5 text-gray-900 dark:text-gray-50 tracking-tight leading-tight',
        2: 'text-2xl font-bold mt-10 mb-4 text-gray-900 dark:text-gray-50 tracking-tight pb-3 border-b border-gray-200 dark:border-gray-800 leading-snug',
        3: 'text-xl font-semibold mt-8 mb-3 text-gray-900 dark:text-gray-100 leading-snug',
        4: 'text-lg font-semibold mt-6 mb-2 text-gray-800 dark:text-gray-200',
        5: 'text-base font-semibold mt-5 mb-1.5 text-gray-800 dark:text-gray-200',
        6: 'text-sm font-semibold mt-4 mb-1 text-gray-700 dark:text-gray-300 uppercase tracking-wider',
      }
      return <Tag key={key} id={block.id} className={classes[block.level] || classes[3]}>{renderInline(block.text)}</Tag>
    }

    case 'paragraph':
      return (
        <p key={key} className="text-gray-700 dark:text-gray-300 leading-7 my-4 max-w-prose">
          {renderInline(block.text)}
        </p>
      )

    case 'image':
      return (
        <figure key={key} className="my-6">
          <img
            src={block.src}
            alt={block.alt || 'Content image'}
            className="rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm max-w-full h-auto"
            loading="lazy"
          />
          {block.alt && (
            <figcaption className="text-center text-xs text-gray-500 dark:text-gray-400 mt-2 italic">
              {block.alt}
            </figcaption>
          )}
        </figure>
      )

    case 'html-embed':
      return <InteractiveHtmlRenderer key={key} content={block.html} />

    case 'code':
      return (
        <div key={key} className="my-6 rounded-xl overflow-hidden border border-gray-200 dark:border-gray-700 shadow-sm">
          {block.lang && (
            <div className="bg-gray-100 dark:bg-gray-800 px-4 py-2 text-xs text-gray-500 dark:text-gray-400 font-mono border-b border-gray-200 dark:border-gray-700 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-red-400" />
              <span className="w-2 h-2 rounded-full bg-yellow-400" />
              <span className="w-2 h-2 rounded-full bg-green-400" />
              <span className="ml-2">{block.lang}</span>
            </div>
          )}
          <pre className="bg-gray-950 dark:bg-gray-900 p-5 overflow-x-auto">
            <code className="text-sm text-gray-100 dark:text-gray-200 font-mono leading-6">{block.code}</code>
          </pre>
        </div>
      )

    case 'blockquote':
      return (
        <blockquote key={key} className="my-6 border-l-4 border-gray-300 dark:border-gray-600 bg-gray-50/80 dark:bg-gray-800/40 pl-5 pr-4 py-3 rounded-r-lg">
          <p className="text-gray-600 dark:text-gray-400 italic leading-7">{renderInline(block.text)}</p>
        </blockquote>
      )

    case 'callout': {
      const styles = {
        info: { border: 'border-blue-200 dark:border-blue-800', bg: 'bg-blue-50/80 dark:bg-blue-900/15', icon: 'ℹ️', label: 'Info', text: 'text-blue-800 dark:text-blue-300' },
        warning: { border: 'border-amber-200 dark:border-amber-800', bg: 'bg-amber-50/80 dark:bg-amber-900/15', icon: '⚠️', label: 'Warning', text: 'text-amber-800 dark:text-amber-300' },
        tip: { border: 'border-emerald-200 dark:border-emerald-800', bg: 'bg-emerald-50/80 dark:bg-emerald-900/15', icon: '💡', label: 'Tip', text: 'text-emerald-800 dark:text-emerald-300' },
        note: { border: 'border-violet-200 dark:border-violet-800', bg: 'bg-violet-50/80 dark:bg-violet-900/15', icon: '📝', label: 'Note', text: 'text-violet-800 dark:text-violet-300' },
      }
      const s = styles[block.kind]
      return (
        <div key={key} className={`my-6 rounded-xl border ${s.border} ${s.bg} p-5`}>
          <div className={`text-xs font-bold uppercase tracking-widest ${s.text} mb-2 flex items-center gap-1.5`}>
            <span>{s.icon}</span> {s.label}
          </div>
          <div className={`text-sm ${s.text} leading-relaxed`}>{renderInline(block.text)}</div>
        </div>
      )
    }

    case 'table':
      return (
        <div key={key} className="my-6 overflow-x-auto rounded-xl border border-gray-200 dark:border-gray-700 shadow-sm">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-gray-50 dark:bg-gray-800/80">
                {block.headers.map((h, j) => (
                  <th key={j} className="px-4 py-3 text-left font-semibold text-gray-700 dark:text-gray-300 text-xs uppercase tracking-wider border-b border-gray-200 dark:border-gray-700">
                    {renderInline(h)}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200 dark:divide-gray-700">
              {block.rows.map((row, j) => (
                <tr key={j} className="hover:bg-gray-50 dark:hover:bg-gray-800/40 transition-colors">
                  {row.map((cell, k) => (
                    <td key={k} className="px-4 py-2.5 text-gray-700 dark:text-gray-300">{renderInline(cell)}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )

    case 'hr':
      return <hr key={key} className="my-10 border-gray-200 dark:border-gray-800" />

    case 'list': {
      const Tag = block.ordered ? 'ol' : 'ul'
      const listClass = block.ordered ? 'list-decimal ml-6 my-4 space-y-2' : 'list-disc ml-6 my-4 space-y-2'
      return (
        <Tag key={key} className={listClass}>
          {block.items.map((item, j) => (
            <li key={j} className="text-gray-700 dark:text-gray-300 leading-7 pl-1.5">{renderInline(item)}</li>
          ))}
        </Tag>
      )
    }

    default:
      return null
  }
}

// ── Inline Rendering ──────────────────────────────────────────────────────

function renderInline(text: string): React.ReactNode {
  const parts: React.ReactNode[] = []
  let remaining = text
  let key = 0

  while (remaining.length > 0) {
    // Skip prompt:// URLs inline
    const promptMatch = remaining.match(/^\(prompt:\/\/[^)]+\)/)
    if (promptMatch && promptMatch.index === 0) {
      remaining = remaining.slice(promptMatch[0].length)
      continue
    }

    const boldMatch = remaining.match(/^\*\*(.+?)\*\*/)
    if (boldMatch && boldMatch.index === 0) {
      parts.push(<strong key={key++} className="font-semibold text-gray-900 dark:text-gray-100">{boldMatch[1]}</strong>)
      remaining = remaining.slice(boldMatch[0].length)
      continue
    }

    const linkMatch = remaining.match(/^\[(.+?)\]\((.+?)\)/)
    if (linkMatch && linkMatch.index === 0) {
      // Skip prompt:// links
      if (linkMatch[2].startsWith('prompt://')) {
        remaining = remaining.slice(linkMatch[0].length)
        continue
      }
      parts.push(
        <a key={key++} href={linkMatch[2]}
          className="text-amber-600 dark:text-amber-400 underline underline-offset-2 decoration-amber-300/50 dark:decoration-amber-700/50 hover:decoration-amber-500 transition-colors font-medium"
          target="_blank" rel="noopener noreferrer">{linkMatch[1]}</a>
      )
      remaining = remaining.slice(linkMatch[0].length)
      continue
    }

    const codeMatch = remaining.match(/^`(.+?)`/)
    if (codeMatch && codeMatch.index === 0) {
      parts.push(
        <code key={key++} className="rounded-md bg-gray-100 dark:bg-gray-800 px-1.5 py-0.5 text-[0.875em] font-mono text-violet-600 dark:text-violet-400 border border-gray-200 dark:border-gray-700">
          {codeMatch[1]}
        </code>
      )
      remaining = remaining.slice(codeMatch[0].length)
      continue
    }

    const italicMatch = remaining.match(/^\*(.+?)\*/)
    if (italicMatch && italicMatch.index === 0 && !boldMatch) {
      parts.push(<em key={key++} className="text-gray-600 dark:text-gray-400">{italicMatch[1]}</em>)
      remaining = remaining.slice(italicMatch[0].length)
      continue
    }

    const strikeMatch = remaining.match(/^~~(.+?)~~/)
    if (strikeMatch && strikeMatch.index === 0) {
      parts.push(<del key={key++} className="text-gray-400">{strikeMatch[1]}</del>)
      remaining = remaining.slice(strikeMatch[0].length)
      continue
    }

    // Inline image
    const inlineImgMatch = remaining.match(/^!\[([^\]]*)\]\(([^)]+)\)/)
    if (inlineImgMatch && inlineImgMatch.index === 0) {
      parts.push(
        <img key={key++} src={inlineImgMatch[2]} alt={inlineImgMatch[1]}
          className="inline-block max-h-64 rounded-lg my-2" loading="lazy" />
      )
      remaining = remaining.slice(inlineImgMatch[0].length)
      continue
    }

    const nextSpecial = remaining.slice(1).search(/[\*`\[~!]/)
    if (nextSpecial === -1) {
      parts.push(remaining)
      remaining = ''
    } else {
      parts.push(remaining.slice(0, nextSpecial + 1))
      remaining = remaining.slice(nextSpecial + 1)
    }
  }

  return parts.length === 1 ? parts[0] : <>{parts}</>
}
